config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :questions
  resources :answers, only: [:create, :destroy, :edit, :udpate]
  resources :responses
  resources :votes, only: [:create, :destroy]
  resources :tags, only: [:index, :create, :show]
  resources :taggings, only: [:create, :destroy]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :responses, as: :responsive
  has_many :votes, as: :votable
end

app/models/question.rb
include ApplicationHelper

class Question < ActiveRecord::Base
  before_create :set_defaults

  belongs_to :user
  has_many :answers
  has_one :best_answer, class_name: 'Answer'
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :votes, as: :votable
  has_many :responses, as: :responsive

  def self.highest_voted
    self.all.sort_by {|q| q.votes.count }.reverse
  end

  def self.most_recent
    self.all.sort_by {|q| q.created_at }.reverse
  end

  def self.trending
    self.all.sort_by {|q| q.visit_count }.reverse
  end

  def tag_names
    tags.pluck(:name).join(", ")
  end

  def tag_names=(tag_names_string)
    tag_names = tag_names_string.split(",").map(&:strip).uniq
    tags = tag_names.map { |name|
      Tag.find_by(name: name) || Tag.new(name: name)
    }
    self.tags = tags
  end


  def increment_visit_count
    self.update_attribute(:visit_count, self.visit_count + 1)
  end


  private
  def set_defaults
    self.slug ||= self.title.downcase.gsub(/[^a-z0-9\s]/i, '').split(' ').join('-')
    self.visit_count ||= 0
  end

end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :user
  belongs_to :responsive, polymorphic: true
  has_many :votes, as: :votable
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :questions, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :question
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :set_defaults

  has_many :questions
  has_many :answers
  has_many :responses
  has_many :votes
  has_secure_password

  def set_defaults
    self.slug ||= self.username.downcase.gsub(/[^a-z0-9\s]/i, '').split(' ').join('-')
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :votable, polymorphic: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @answer = Answer.new(answer_params)
    @answer.user = current_user

    respond_to do |format|
      if @answer.save
        format.html { redirect_to question_path(@answer.question, {:id => @answer.question}), notice: 'Answer was successfully created.' }
      else
        format.html { redirect_to question_path(@answer.question), notice: 'Could not create answer.' }
      end
    end
  end

  def update
  end

  def destroy
  end

  private
  def answer_params
    params.require(:answer).permit(:content, :question_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @_current_user ||= session[:user_id]
    User.find_by(id: session[:user_id])
  end

  helper_method :current_user

  def logged_in?
    !!current_user
  end
  helper_method :logged_in?
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :redirect_to_root, unless: :'logged_in?', only: [:new]

  def index
    if params[:sort] == 'most_recent'
      @questions = Question.most_recent
    elsif params[:sort] == 'trending'
      @questions = Question.trending
    else
      @questions = Question.highest_voted
    end
  end

  def show
    @question.increment_visit_count
    @answer = Answer.new
  end

  def new
    @question = Question.new
    @tagging = Tagging.new
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to question_path(@question)
    else
      flash[:notice] = 'Question not posted'
      render :new
    end
  end

  def update
  end

  def destroy
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
      params.require(:question).permit(:title, :content, :tag_names)
  end

  def redirect_to_root
    redirect_to root_path
    flash[:notice] = 'Must be logged in to post a question'
  end

  def increment_visit_count
    self.update_attribute(:visit_count, self.visit_count + 1)
  end

end

#  questions GET    /questions(.:format)          questions#index
#               POST   /questions(.:format)          questions#create
#  new_question GET    /questions/new(.:format)      questions#new
# edit_question GET    /questions/:id/edit(.:format) questions#edit
#      question GET    /questions/:id(.:format)      questions#show
#               PATCH  /questions/:id(.:format)      questions#update
#               PUT    /questions/:id(.:format)      questions#update
#               DELETE /questions/:id(.:format)      questions#destroy

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def create

  end

  def update
  end

  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back"
      redirect_to root_path
    else
      flash[:notice] = "Invalid email or password"
      render 'new'
    end
  end

  def destroy
    logout
    flash[:notice] = "Come back soon"
    redirect_to questions_path
  end

  private
  def logout
    @_current_user = nil
    session[:user_id] = nil
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show]

  def show
  end

  def index
    @tags = Tag.all
  end

  private
  def set_tag
    @tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Registered successfully'
      redirect_to root_path
    else
      flash[:notice] = 'Registration failed'
      render :new
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Profile updated"
      render :show
    else
      flash[:notice] = "Profile not updated"
      render :edit
    end
  end

  def destroy
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
      params.require(:user).permit(:username, :real_name, :email, :password, :website, :location, :age)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    if response_params[:responsible_type] == "question"
      @responsible = Question.find_by_id(response_params[:responsible_id])
    else
      @responsible = Answer.find_by_id(response_params[:responsible_id])
    end

    @response = @responsible.responses.new(content: response_params[:content])

    @response.user = current_user

    @question = Question.find_by_id(response_params[:question_id])

    respond_to do |format|
      if @response.save
        format.html { redirect_to question_path(@question, {:id => @question}), notice: 'Comment successfully posted.' }
        format.js { redirect_to question_path(@question, {:id => @question}), notice: 'Comment successfully posted.' }
      else
        format.html { redirect_to question_path(@question), notice: 'Could not post comment.' }
      end
    end
  end

  # the votable object can be easily found with
  # votable = vote.votable

end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date
    self.strftime("%m/%d/%Y at %I:%M%p")
  end
end

app/views/comments/new.html.erb
<h3>Add Your Comment</h3>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class='flash'>
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div id='header'>
  <ul>
      <li id='home-page-link'><%= link_to "Fridge Overflow", root_path %></li>
    <% if logged_in? %>
      <li><%= link_to "Logout", logout_path, method: :delete %></li>
      <li><%= link_to "Profile", user_path(current_user.id) %></li>
    <% else %>
      <li><%= link_to "Login", login_path %></li>
      <li><%= link_to "Register", new_user_path %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/_nav.html.erb
<div id='nav'>
  <%= link_to 'Ask Question', new_question_path %>
  <%= link_to 'Questions', questions_path %>
  <%= link_to 'Users', users_path %>
  <%= link_to 'Tags', tags_path %>
</div><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FridgeOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= render 'layouts/flash' %>
<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='question-form'>
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_area :title %>
    </div>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </div>
    <div class="field">
      <%= f.label :tag_names, "Tags (separated by commas) " %><br>
      <%= f.text_field :tag_names %>
    </div>
  <div>
    <div class="actions">
      <%= f.submit "Finish" %>
    </div>
  </div>
<% end %>

app/views/questions/index.html.erb
<h1 class='center'>FRIDGE OVERFLOW</h1>

<%= render 'layouts/nav' %>

<table id='question_index'>
  <thead>
    <th class='short-column'>Votes</th>
    <th class='short-column'>Answers</th>
    <th class='short-column'>Views</th>
    <th class='long-column'><%= link_to "Highest-Voted", {sort: 'highest_voted'} %> --- <%= link_to "Most Recent", {sort: 'most_recent'} %> --- <%= link_to "Trending", {sort: 'trending'}%></th>
  </thead>
  <tbody>
    <% @questions.each do |question|%>
      <tr>
        <td class='center'><%= question.votes.count %></td>
        <td class='center'><%= question.answers.count %></td>
        <td class='center'><%= question.visit_count %></td>
        <td class='big'><%= link_to question.title, question %><p>Submitted by <%= link_to question.user.username, user_path(question.user) %> on <%= question.created_at.format_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/questions/new.html.erb
<h1 class='question_header'>Post Your Question</h1>

<%= render 'form' %><br>

<%= link_to 'Back', root_path %>

app/views/questions/show.html.erb
<!-- Question Content -->
<h2><%= @question.title %></h2>
<p><%= @question.content%></p>
<!-- Question: Add Comment -->
<a id="addComment" href="/organizations/new">add a comment</a>


<!-- Question's Answers -->
<h4>Answers</h4>
<ul>
<% @question.answers.each do |ans| %>
  <li>
  <%= ans.created_at%><%= ans.content %> - <%= ans.user %>
  <br>
  </li>
<% end %>
</ul>
<!-- Create A New Answer -->
<h4>Your Answer</h4>

<%= form_for(@answer) do |f| %>

<%= f.hidden_field :question_id, value: @question.id %>

<%= f.label :content %>
<br>
<%= f.text_field :content, size: 200 %>
<br>

<%= f.submit "Post Your Answer" %>

<% end %>

app/views/tags/index.html.erb
<h1 class='center'>TAGS</h1>

<%= render 'layouts/nav' %>

<% @tags.each do |tag| %>
  <div class='tag-box'>
    <%= link_to tag.name, tag_path(tag) %><br>
  </div>
<% end %>

app/views/tags/show.html.erb
<h1 class='center'><%= @tag.name %></h1>

<%= render 'layouts/nav' %>

<% @tag.questions.each do |q| %>
  <%= link_to q.title, question_path(q) %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='user-form'>
    <div class="field">
      <%= f.label :username, "Enter username" %>
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <%= f.label :real_name, "Enter full name" %>
      <%= f.text_field :real_name %>
    </div>
    <div class="field">
      <%= f.label :email, "Enter email" %>
      <%= f.email_field :email %>
    </div>
    <div class="field">
      <%= f.label :password, "Enter password" %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirm password" %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
      <%= f.label :website, "Enter website" %>
      <%= f.text_field :website %>
    </div>
    <div class="field">
      <%= f.label :location, "Enter location" %>
      <%= f.text_field :location %>
    </div>
    <div class="field">
      <%= f.label :age, "Enter age" %>
      <%= f.text_field :age %>
    </div>
    <div class="actions">
      <%= f.submit "Finish" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path %>

app/views/users/index.html.erb
<h1 class='center'>USERS</h1>

<%= render 'layouts/nav' %>

<% @users.each do |user| %>
  <div class='user-box'>
    <%= link_to user.username, user_path(user) %><br>
    <%= user.location %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Register</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class='center'><%= @user.username %></h1>

<%= render 'layouts/nav' %>

<h1>Profile</h1>
<div class='user-form'>
  <p><strong>Username: </strong><%= @user.username %></p>
  <p><strong>Full name: </strong><%= @user.real_name %></p>
  <p><strong>Email: </strong><%= @user.email %></p>
  <p><strong>Website: </strong><%= @user.website %></p>
  <p><strong>Location: </strong><%= @user.location %></p>
  <p><strong>Age: </strong><%= @user.age %></p>
</div>

<%= link_to 'Edit profile', edit_user_path(@user) %>